package com.giaolang.mamnguqua.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity - Trái cây (Fruit)
 *
 * Represents a fruit product in the system with following attributes:
 * - id: Unique identifier (Primary Key)
 * - name: Tên trái cây (3-100 characters, required)
 * - desc: Mô tả chi tiết trái cây (10-500 characters, required)
 * - price: Giá bán (0.01 - 9999999999.99, 2 decimal places)
 * - createdAt: Thời gian tạo (auto-generated)
 * - updatedAt: Thời gian cập nhật lần cuối (auto-updated)
 *
 * Validation Rules:
 * - name: Bắt buộc, độ dài 3-100 ký tự
 * - desc: Bắt buộc, độ dài 10-500 ký tự
 * - price: Dương, tối đa 2 chữ số thập phân
 *
 * Database Table: fruits
 *
 * @author giáo.làng with AI support
 * @version 2026.0217
 * @since 2026
 */
@Entity
@Table(name = "Fruit", indexes = {
        @Index(name = "idx_fruit_name", columnList = "Name"),
        @Index(name = "idx_fruit_created_at", columnList = "CreatedAt")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Fruit {

    /**
     * Primary Key - Auto generated by database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Id")
    private Long id;

    /**
     * Tên trái cây
     * Constraints: NOT NULL, length 3-100
     */
    @NotBlank(message = "Tên trái cây không được để trống")
    @Size(min = 2, max = 100, message = "Tên trái cây phải từ 2 đến 100 ký tự")
    @Column(name = "Name", nullable = false, columnDefinition = "nvarchar(100)")
    private String name;

    /**
     * Mô tả chi tiết trái cây
     * Constraints: NOT NULL, length 10-500
     */
    @NotBlank(message = "Mô tả không được để trống")
    @Size(min = 10, max = 500, message = "Mô tả phải từ 10 đến 500 ký tự")
    @Column(name = "Description", nullable = false, columnDefinition = "nvarchar(500)")
    private String desc;

    /**
     * Giá bán trái cây (VNĐ)
     * Constraints: POSITIVE, precision 10, scale 2
     */
    @Positive(message = "Giá trái cây phải lớn hơn 0")
    @DecimalMin(value = "0.01", message = "Giá trái cây phải ít nhất 0.01")
    @Digits(integer = 10, fraction = 2, message = "Giá phải có tối đa 2 chữ số thập phân")
    @Column(name = "Price", nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Thời gian tạo record (auto-generated)
     * Constraints: NOT NULL, non-updatable
     */
    @Column(name = "CreatedAt", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Thời gian cập nhật lần cuối
     * Auto-updated mỗi khi record được cập nhật
     */
    @Column(name = "UpdatedAt", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Pre-persist callback - Chạy trước khi entity được lưu lần đầu
     * Tự động set thời gian tạo và cập nhật
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Pre-update callback - Chạy trước khi entity được cập nhật
     * Tự động update thời gian cập nhật
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
