spring.application.name=tên-project-đặt-100%-giống-đề-thi



# CẤU HÌNH cổng lắng nghe của Tomcat. PORT: Là ID định danh cho 1 app 
# Nếu dùng cổng 8080 thì không cần gõ dòng này. Port hợp lệ từ 0 -> 65.535
# ------------------------------------------------------------------------------
server.port=6969



# KHAI BÁO kết nối CSDL SQL Servcer ở đây. Không kết nối thành công CSDL thì không thể khởi động Tomcat
# Tên Database 100% giống đề thi; username: sa | password: pass.của.sinh.viên 
# Lúc nộp bài NHỚ sửa lại password như trong file đề thi
# ------------------------------------------------------------------------------
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=THAY_TÊN_DB_CỦA_ĐỀ_THI;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=pass.của.sinh.viên.lúc.nộp.bài.nhớ.chỉnh.lại.theo.đề.thi
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver



# CẤU HÌNH JPA/Hibernate bao gồm các options: 
# - CODE FIRST: Tạo table từ code của class chứa @Entity 
#   -> Thiết lập: spring.jpa.hibernate.ddl-auto=create hoặc update
# - DATABASE FIRST: Tự động chạy 2 file SQL Script (schema.sql, data.sql) khi run app để tạo table và chèn sẵn data
#   -> Thiết lập: spring.jpa.hibernate.ddl-auto=none và spring.sql.init.mode=always
# - In ra câu SQL do Hibernate tự tạo trong quá trình thực thi các lệnh JPA/Hibernate để tiện debug
# ------------------------------------------------------------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CHỈ LÀM PHẦN NÀY NẾU CHƠI HỆ DB FIRST; nhớ phải có thêm tập tin sql để CREATE TABLE và INSERT DATA
spring.sql.init.mode=always



# CẤU HÌNH Thymeleaf
# cache=false: Giúp cập nhật giao diện mà không cần khởi động lại app
# prefix: Nơi chứa UI/các trang thymeleaf
# suffix: Mặc định Thymeleaf sẽ tìm file .html.
# ------------------------------------------------------------------------------
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
