spring.application.name=department-service

server.port=8081

# DB Configuration
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MSS301_2026_PE;encrypt=false;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ddl-auto=none to use existing tables (and disable schema modification)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs